import { useState } from "react";
import { Check, TriangleAlert, Search, CloudOff, ChevronRight } from "lucide-react";

// RethinkerKit — the Rethinker mockup's components, ported 1:1 into our
// architecture (React + our Tailwind tokens) so the whole pattern POOL
// sits next to our real components. We then map these onto our own
// schedule UI (see DESIGN-SYSTEM.md). Faithful to
// examples/schedule/mockups/rethinker.html; colours are the dark-theme
// literals the mockup used — we're matching the dark mockup first.
//
// Nothing here is wired to data; these are presentational specimens.

// ── shared bits ─────────────────────────────────────────────────────
export function Eyebrow({ children, className = "" }) {
  return (
    <span className={"font-ui text-[11px] font-semibold uppercase tracking-[0.14em] " + className}>
      {children}
    </span>
  );
}

// segment fills for the load-meter lanes / silhouettes
const HATCH_ACCENT =
  "repeating-linear-gradient(45deg,rgba(173,200,173,0.55) 0 3px,rgba(173,200,173,0.16) 3px 7px)";
const HATCH_EVENT =
  "repeating-linear-gradient(45deg,#5dd585 0 7px,#4cc278 7px 9px)";
const HATCH_HOLE =
  "repeating-linear-gradient(45deg,rgba(230,184,90,0.18) 0 4px,transparent 4px 8px)";

// Resolve a "token" or "token/alpha" spec to an inline background — used
// by the silhouette / mini-spine / heat bars, where dynamic Tailwind
// class names (`bg-${c}`) would never be generated by the JIT scanner.
const TOKEN = {
  resolved: "var(--c-resolved)",
  "accent-deep": "var(--c-accent-deep)",
  "cat-fm": "var(--c-cat-fm)",
  warn: "var(--c-warn)",
  "cat-processing": "var(--c-cat-processing)",
  "surface-alt": "var(--c-surface-alt)",
};
function barStyle(spec) {
  const [name, alpha] = String(spec).split("/");
  const c = TOKEN[name] || "var(--c-border)";
  return alpha
    ? { background: `color-mix(in srgb, ${c} ${alpha}%, transparent)` }
    : { background: c };
}

function segStyle(kind) {
  switch (kind) {
    case "done":      return { background: "var(--c-resolved)" };
    case "committed": return { background: "var(--c-accent-deep)" };
    case "open":      return { background: HATCH_ACCENT };
    case "event":     return { background: HATCH_EVENT };
    case "hole":
      return {
        boxShadow: "inset 0 0 0 1.5px var(--c-warn)",
        backgroundImage: HATCH_HOLE,
      };
    default:          return {};
  }
}

// ── 1 · LoadMeter (the lane) ────────────────────────────────────────
export function LoadTrack({ segments, height = 13, className = "" }) {
  return (
    <div
      className={"relative flex overflow-hidden bg-surface-alt " + className}
      style={{ height, boxShadow: "inset 0 0 0 1px #2a322a" }}
    >
      {segments.map((s, i) => (
        <div key={i} className="h-full" style={{ width: s.pct + "%", ...segStyle(s.kind) }} />
      ))}
    </div>
  );
}

export function LoadMeter({ lanes }) {
  return (
    <div className="flex flex-col gap-1">
      {lanes.map((lane, i) => (
        <div key={lane.name ?? i} className="flex items-center gap-2">
          <span className="w-[42px] shrink-0 font-ui text-[11px] font-semibold uppercase tracking-[0.04em] text-muted">
            {lane.name}
          </span>
          <LoadTrack segments={lane.segments} className="flex-1" />
          <span className={"shrink-0 min-w-[30px] text-right font-ui text-[11px] font-semibold "
            + (lane.metaTone === "warn" ? "text-warn"
              : lane.metaFaint ? "text-faint" : "text-dim")}>
            {lane.meta}
          </span>
        </div>
      ))}
    </div>
  );
}

// ── 2 · Now-marker (hairline rule + dot) ────────────────────────────
export function NowRule({ label = "NOW 9:40" }) {
  return (
    <div className="relative py-2">
      <div className="relative h-0" style={{ borderTop: "1.5px solid var(--c-resolved)" }}>
        <span
          className="absolute -top-1 left-0 w-[7px] h-[7px] rounded-full"
          style={{ background: "var(--c-resolved)", boxShadow: "0 0 0 3px rgba(76,186,133,0.22)" }}
        />
      </div>
      {label && (
        <Eyebrow className="text-resolved text-[9px] mt-1 block tracking-[0.08em]">{label}</Eyebrow>
      )}
    </div>
  );
}

// ── 3 · Seal stamp (a sealed block's worked-window stamp) ───────────
export function SealStamp({ children = "Sealed · Jim 6:08–8:10 · 7/7" }) {
  return (
    <span className="inline-flex items-center gap-[7px] font-ui text-[11px] font-semibold tracking-[0.02em] text-resolved">
      <Check size={12} strokeWidth={3} />
      {children}
    </span>
  );
}

// ── 4 · Rounds checkbox (the 28px tap target) ───────────────────────
export function RoundsCheckbox({ defaultChecked = false, label }) {
  const [done, setDone] = useState(defaultChecked);
  return (
    <button
      type="button"
      onClick={() => setDone((d) => !d)}
      className="flex items-center gap-3 text-left"
    >
      <span
        className={"shrink-0 w-7 h-7 inline-flex items-center justify-center border-2 transition-colors "
          + (done ? "bg-resolved border-resolved text-on-accent" : "bg-bg border-line text-transparent")}
      >
        <Check size={16} strokeWidth={3} className={done ? "opacity-100" : "opacity-0"} />
      </span>
      {label && (
        <span className={"text-[14px] " + (done ? "text-faint line-through" : "text-fg")}>{label}</span>
      )}
    </button>
  );
}

// ── 5 · Day-load silhouette (per-block two-stacks; height = load) ────
export function DaySilhouette({ blocks }) {
  return (
    <div className="flex items-end gap-1 h-9">
      {blocks.map((b, i) => (
        <div key={i} className="flex-1 flex flex-col justify-end gap-px" title={b.title}>
          <div style={{ height: b.top.h, ...segStyle(b.top.kind) }} />
          <div style={{ height: b.bottom.h, ...segStyle(b.bottom.kind) }} />
        </div>
      ))}
    </div>
  );
}

// ── 6 · Event band (left colour bar + bordered card) ────────────────
export function EventBand({ kindColor = "var(--c-cat-fm)", title, time, sub }) {
  return (
    <div className="flex items-stretch gap-2">
      <div className="w-1 shrink-0" style={{ background: kindColor }} />
      <div className="flex-1 border px-3 py-2" style={{ borderColor: "color-mix(in srgb, var(--c-cat-fm) 40%, transparent)", background: "var(--c-surface)" }}>
        <div className="flex items-baseline justify-between gap-2">
          <span className="text-[14px] font-semibold text-fg">{title}</span>
          <span className="font-ui text-[11px] text-cat-fm font-semibold">{time}</span>
        </div>
        {sub && <div className="text-[12px] text-dim mt-1 leading-snug">{sub}</div>}
      </div>
    </div>
  );
}

// ── 7 · Needs-cover card (man-down → cover) ─────────────────────────
export function NeedsCoverCard({
  work = "Wash eggs · House",
  detail = "Assigned to James, off-site at the market until 1:00p. The window opens 1:00–4:00.",
  coverLabel = "Jim covers — I've got it",
}) {
  return (
    <div className="border" style={{ borderColor: "color-mix(in srgb, var(--c-warn) 50%, transparent)", background: "var(--c-surface-alt)" }}>
      <div className="px-3 py-2.5 flex items-center gap-2 border-b" style={{ borderColor: "color-mix(in srgb, var(--c-warn) 25%, transparent)" }}>
        <TriangleAlert size={16} className="text-warn shrink-0" />
        <span className="text-[14px] font-semibold text-fg">Needs cover</span>
      </div>
      <div className="px-3 py-3">
        <div className="text-[14px] text-fg font-medium">{work}</div>
        <div className="text-[12px] text-dim mt-1 leading-snug">{detail}</div>
        <div className="font-ui text-[12px] text-dim mt-2.5">Who can cover?</div>
        <button className="w-full mt-2 bg-warn text-on-accent border-0 py-2.5 cursor-pointer font-ui text-[12px] font-bold uppercase tracking-[0.1em]">
          {coverLabel}
        </button>
        <div className="font-ui text-[11px] text-faint mt-2.5 leading-snug">
          The acknowledgment is the record — the hole closes green in the
          coverer's lane.
        </div>
      </div>
    </div>
  );
}

// ── 8 · Confirm card ("Ready to plan", draft → confirm) ─────────────
export function ConfirmCard({
  title = "Ready to plan Tuesday?",
  body = "42 items across 5 blocks. 6 musts are non-negotiable; the rest is today's discretionary work. Confirming drops the accountability anchor.",
  cta = "Confirm the day",
}) {
  return (
    <div className="border border-accent-deep p-3.5" style={{ background: "color-mix(in srgb, var(--c-accent-deep) 12%, transparent)" }}>
      <div className="text-[14px] text-fg font-semibold leading-snug">{title}</div>
      <div className="text-[12px] text-dim mt-1.5 leading-snug">{body}</div>
      <button className="w-full mt-3 bg-accent text-on-accent border-0 py-2.5 cursor-pointer font-ui text-[12px] font-bold uppercase tracking-[0.12em]">
        {cta}
      </button>
    </div>
  );
}

// ── 9 · Source-change strip ("N changes since you confirmed") ───────
export function SourceChangeStrip({
  summary = "1 change since you confirmed",
  body = "Feed delivery moved to today, ~2:00p (was Thu). It lands in James's Early-afternoon lane.",
}) {
  return (
    <div className="border" style={{ borderColor: "color-mix(in srgb, var(--c-warn) 50%, transparent)", background: "var(--c-surface-alt)" }}>
      <div className="w-full flex items-center gap-2.5 px-3 py-2 text-left">
        <TriangleAlert size={14} className="text-warn shrink-0" />
        <span className="text-[12.5px] text-fg font-medium flex-1">{summary}</span>
        <Eyebrow className="text-[10px] text-warn">Review</Eyebrow>
      </div>
      <div className="px-3 pb-3 pt-0.5 border-t" style={{ borderColor: "color-mix(in srgb, var(--c-warn) 25%, transparent)" }}>
        <div className="text-[12px] text-dim leading-snug mt-2">{body}</div>
        <div className="flex gap-2 mt-2.5">
          <button className="bg-accent text-on-accent border-0 px-3 py-1.5 cursor-pointer font-ui text-[10px] uppercase tracking-[0.12em] font-semibold">Add to today</button>
          <button className="border border-line text-dim bg-transparent px-3 py-1.5 cursor-pointer font-ui text-[10px] uppercase tracking-[0.12em] font-semibold">Dismiss</button>
        </div>
      </div>
    </div>
  );
}

// ── 10 · Block card (the spine's unit; sealed / now-open shells) ────
export function BlockCard({ name, note, state = "default", children }) {
  const sealed = state === "sealed";
  const now = state === "now";
  return (
    <div
      className={"px-3 py-2.5 " + (now ? "border-2" : "border ") + (sealed ? " opacity-70" : "")}
      style={{
        borderColor: now ? "color-mix(in srgb, var(--c-resolved) 55%, transparent)" : "var(--c-border)",
        background: sealed ? "color-mix(in srgb, var(--c-surface) 40%, transparent)" : "var(--c-surface)",
      }}
    >
      <div className="flex items-center gap-2">
        <span className={"font-heading text-[15px] font-semibold flex-1 -tracking-[0.01em] "
          + (sealed ? "text-dim" : "text-fg")}>{name}</span>
        {note && !sealed && <Eyebrow className="text-[10px] text-muted">{note}</Eyebrow>}
        {sealed && <SealStamp />}
      </div>
      {children && <div className="mt-2">{children}</div>}
    </div>
  );
}

// ── 12 · Outbox indicator (offline / queued writes) ────────────────
export function OutboxIndicator({ count = 1 }) {
  return (
    <span className="inline-flex items-center gap-1.5 font-ui text-[11px] font-semibold text-warn whitespace-nowrap">
      <CloudOff size={13} /> {count} queued
    </span>
  );
}

// ── 13 · Desktop two-lane ribbon (the wide-tier spine) ──────────────
// A horizontal time axis (6a–8p) with two person-lanes; segments are
// absolutely positioned by left%/width% along the axis. Hardcoded sample
// (the mockup's market Tuesday) — presentational specimen.
const RIBBON_GRID = {
  background:
    "repeating-linear-gradient(to right,transparent 0,transparent calc(7.6923% - 1px),"
    + "var(--c-surface-alt) calc(7.6923% - 1px),var(--c-surface-alt) 7.6923%)",
};
function RibbonSeg({ left, width, style, className = "", title, children }) {
  return (
    <div
      className={"absolute top-1.5 bottom-1.5 flex flex-col justify-center px-2 overflow-hidden font-ui " + className}
      style={{ left: left + "%", width: width + "%", ...style }}
      title={title}
    >
      {children}
    </div>
  );
}
const HOURS = ["6a","7a","8a","9a","10a","11a","12p","1p","2p","3p","4p","5p","6p"];

export function DesktopRibbon() {
  return (
    <div className="border border-line bg-bg">
      {/* toolbar */}
      <div className="flex items-center justify-between px-5 py-3 border-b border-line" style={{ background: "color-mix(in srgb, var(--c-surface) 60%, transparent)" }}>
        <div className="flex items-center gap-3">
          <span className="font-heading text-[20px] font-bold text-fg">Tue Jun 24</span>
          <span className="font-ui text-[12px] text-dim">market day</span>
          <span className="inline-flex items-center gap-1.5 text-[11px] font-semibold text-resolved ml-1">
            <Check size={12} strokeWidth={3} /> Confirmed
          </span>
        </div>
        <div className="flex items-center gap-1 font-ui text-[12px]">
          <span className="px-3 py-1.5 bg-surface-alt text-fg font-semibold">Day</span>
          <span className="px-3 py-1.5 text-dim">Week</span>
          <span className="px-3 py-1.5 text-dim">Month</span>
          <span className="ml-2 px-3 py-1.5 border border-line text-dim inline-flex items-center gap-1.5">
            <Search size={12} /> Add
          </span>
        </div>
      </div>

      {/* time axis */}
      <div className="px-5 pt-7 pb-2">
        <div className="grid text-[10px] font-ui text-faint border-b border-line pb-1" style={{ gridTemplateColumns: "repeat(13,1fr)" }}>
          {HOURS.map((h) => <span key={h}>{h}</span>)}
        </div>
      </div>

      {/* lanes */}
      <div className="px-5 pb-4 flex flex-col gap-2">
        {/* Jim */}
        <div className="flex items-stretch gap-3">
          <div className="w-16 shrink-0 flex items-center font-ui text-[12px] font-semibold text-dim">
            Jim <span className="text-resolved ml-1.5 text-[10px]">▷6:08</span>
          </div>
          <div className="relative flex-1 h-12 border border-line" style={RIBBON_GRID}>
            {/* now-line */}
            <div className="absolute z-20" style={{ left: "28.2%", top: -18, bottom: -6, width: 1.5, background: "var(--c-resolved)" }}>
              <span className="absolute font-ui text-[9px] font-bold tracking-[0.08em] text-resolved whitespace-nowrap" style={{ top: -16, left: -26 }}>NOW 9:40</span>
            </div>
            <RibbonSeg left={0} width={16.5} className="text-on-accent" style={{ background: "color-mix(in srgb, var(--c-resolved) 85%, transparent)" }}>
              <span className="text-[11px] font-semibold">Morning ✓ 7/7</span>
            </RibbonSeg>
            <RibbonSeg left={23} width={30.7} className="text-on-accent" style={{ background: "var(--c-accent-deep)" }}>
              <span className="text-[11px] font-semibold">Midmorning · 2/8</span>
              <span className="text-[9.5px] opacity-80">+ pressure-wash (should)</span>
            </RibbonSeg>
            <RibbonSeg left={46.1} width={3.8} title="break 12:00–12:30"
              style={{ background: "repeating-linear-gradient(45deg,var(--c-border) 0 4px,transparent 4px 8px)" }} />
            <RibbonSeg left={53.8} width={23} className="text-on-accent" style={{ background: "color-mix(in srgb, var(--c-accent-deep) 85%, transparent)" }}>
              <span className="text-[11px] font-semibold">Early afternoon</span>
              <span className="text-[9.5px] opacity-80">+ Clearing brush · D pasture</span>
            </RibbonSeg>
            <RibbonSeg left={76.9} width={23} className="text-on-accent" style={{ background: "color-mix(in srgb, var(--c-accent-deep) 70%, transparent)" }}>
              <span className="text-[11px] font-semibold">Late afternoon</span>
            </RibbonSeg>
          </div>
        </div>
        {/* James */}
        <div className="flex items-stretch gap-3">
          <div className="w-16 shrink-0 flex items-center font-ui text-[12px] font-semibold text-dim">
            James <span className="text-cat-fm ml-1.5 text-[10px]">▷mkt</span>
          </div>
          <div className="relative flex-1 h-12 border border-line" style={RIBBON_GRID}>
            <RibbonSeg left={0} width={12.5} className="text-fg" style={{ background: "color-mix(in srgb, var(--c-resolved) 45%, transparent)" }}>
              <span className="text-[10px] font-semibold">Prep ✓</span>
            </RibbonSeg>
            <RibbonSeg left={15.4} width={7.7} title="setup buffer 8–9"
              style={{ background: "repeating-linear-gradient(45deg,#5dd585 0 6px,transparent 6px 12px)" }}>
              <span className="text-[9px] text-cat-fm font-semibold">buffer</span>
            </RibbonSeg>
            <RibbonSeg left={23} width={30.7} style={{ background: "repeating-linear-gradient(45deg,#5dd585 0 9px,#4cc278 9px 12px)" }}>
              <span className="text-[11px] font-bold text-[#0d1410]">Farmers market</span>
              <span className="text-[9.5px] text-[#0d1410]/80">9:00–1:00 · off-site</span>
            </RibbonSeg>
            <RibbonSeg left={53.8} width={13} title="Wash eggs — needs cover"
              style={{ boxShadow: "inset 0 0 0 1.5px var(--c-warn)", backgroundImage: "repeating-linear-gradient(45deg,rgba(230,184,90,0.16) 0 4px,transparent 4px 8px)" }}>
              <span className="text-[10px] font-semibold text-warn">Wash eggs</span>
              <span className="text-[9px] text-warn/80">needs cover</span>
            </RibbonSeg>
            <RibbonSeg left={76.9} width={23} className="text-on-accent" style={{ background: "color-mix(in srgb, var(--c-accent-deep) 60%, transparent)" }}>
              <span className="text-[11px] font-semibold">Late afternoon</span>
            </RibbonSeg>
          </div>
        </div>
      </div>

      {/* combined silhouette */}
      <div className="px-5 pb-3">
        <Eyebrow className="text-[10px] text-faint mb-1.5 block tracking-[0.12em]">Day load — combined silhouette</Eyebrow>
        <div className="flex items-end gap-0.5 h-10 border-b border-line">
          {[["resolved/70",60],["resolved/70",72],["cat-fm/60",46],["accent-deep",88],
            ["accent-deep",80],["accent-deep",64],["accent-deep/60",30],["warn",96],
            ["accent-deep",70],["accent-deep/80",50],["accent-deep/80",62],
            ["accent-deep/70",44],["accent-deep/60",36]].map(([c, h], i) => (
            <div key={i} className="flex-1" style={{ height: h + "%", ...barStyle(c) }}
              title={c === "warn" ? "man-down — over capacity" : ""} />
          ))}
        </div>
      </div>
    </div>
  );
}

// ── 14 · Week mini-spines + should-heat row ─────────────────────────
function MiniSpine({ label, labelTone = "text-dim", frame = "border-line", stacks }) {
  return (
    <div>
      <div className={"font-ui text-[11px] mb-1.5 text-center " + labelTone}>{label}</div>
      <div className={"flex items-end justify-center gap-1 h-16 border py-1.5 " + frame}
        style={{ background: frame === "border-line" ? "color-mix(in srgb, var(--c-surface) 30%, transparent)" : "var(--c-surface)" }}>
        {stacks.map((cells, i) => (
          <div key={i} className="flex flex-col-reverse gap-px">
            {cells.map(([c, h], j) => (
              <div key={j} className="w-[7px]" style={{ height: h, ...barStyle(c) }} title={c} />
            ))}
          </div>
        ))}
      </div>
    </div>
  );
}

export function WeekSpines() {
  return (
    <div>
      <Eyebrow className="text-[10px] text-faint mb-3 block tracking-[0.12em]">This week — fullness spines + should-heat</Eyebrow>
      <div className="grid grid-cols-7 gap-3">
        <MiniSpine label="Sun 22" stacks={[[["accent-deep/50",8],["accent-deep/50",14],["accent-deep/50",7]]]} />
        <MiniSpine label="Mon 23" stacks={[[["accent-deep/60",18],["accent-deep/60",22],["accent-deep/60",12]]]} />
        <MiniSpine label="Tue 24 · today" labelTone="text-resolved font-bold" frame="border-2 border-resolved/55"
          stacks={[[["resolved",24],["accent-deep",30],["cat-fm",18]], [["accent-deep",20],["warn",14]]]} />
        <MiniSpine label="Wed 25" stacks={[[["accent-deep/70",20],["accent-deep/70",24],["accent-deep/70",14]]]} />
        <MiniSpine label="Thu 26 · proc." labelTone="text-cat-processing font-semibold" frame="border-cat-processing/40"
          stacks={[[["accent-deep",26],["cat-processing/70",34],["accent-deep",16]]]} />
        <MiniSpine label="Fri 27" stacks={[[["accent-deep/60",14],["accent-deep/60",18],["accent-deep/60",10]]]} />
        <MiniSpine label="Sat 28" stacks={[[["resolved/70",20],["cat-fm",26],["accent-deep/60",12]]]} />
      </div>
      {/* should-escalation heat row */}
      <div className="mt-3 grid grid-cols-7 gap-3 items-center">
        <Eyebrow className="col-span-7 text-[10px] text-faint tracking-[0.12em]">
          Should-escalation · "Pressure wash nest boxes" warming toward Thu processing
        </Eyebrow>
        {["warn/15","warn/25","warn/40","warn/55","cat-processing/70","surface-alt","surface-alt"].map((c, i) => (
          <div key={i} className={"h-2.5" + (i === 2 ? " ring-1 ring-warn/60" : "")} style={barStyle(c)} />
        ))}
      </div>
    </div>
  );
}

// ── 11 · Search-to-add (dedup field + result) ───────────────────────
export function SearchToAdd() {
  return (
    <div className="bg-bg p-3.5 border border-line">
      <div className="flex items-center gap-2.5 border border-accent/40 bg-surface px-3 py-2.5">
        <Search size={16} className="text-accent shrink-0" />
        <span className="text-[15px] text-fg flex-1">Fill waterer</span>
        <Eyebrow className="text-[10px] text-faint tracking-[0.08em]">esc</Eyebrow>
      </div>
      <Eyebrow className="text-[10px] text-faint block px-1 pt-3 pb-1">Chore · dedup'd</Eyebrow>
      <button className="w-full flex items-center gap-3 px-3 py-2.5 bg-surface border border-line text-left">
        <Check size={15} className="text-resolved shrink-0" />
        <span className="flex-1">
          <span className="block text-[14px] text-fg">Fill waterer</span>
          <span className="block text-[11px] text-faint">appears at 5 places — pick one</span>
        </span>
      </button>
    </div>
  );
}
