-- ============================================================================
-- 0005_events_products_inventory.sql
-- ============================================================================
-- Third slice of the reference-data migration. Covers the outward-facing
-- schedule and the product catalog:
--
--   event_kinds          — farmers markets, pop-ups, processing days, etc.
--   event_instances      — concrete instances (recurring or dated)
--   product_kinds        — SKU catalog with size brackets
--   egg_lots             — FIFO egg inventory (schema only, empty)
--   chicken_lots         — FIFO chicken inventory (schema only, empty)
--
-- Seed blocks for event_kinds / event_instances / product_kinds are
-- generated by scripts/gen-batch3-seed.mjs from nff-data.json and
-- concatenated onto the end of this file at generation time.
--
-- Not migrated this batch:
--   - data.costs        (flat config; no editing UI planned near-term)
--   - data.inventory.modelNotes   (display-only prose; stays in JSON)
--
-- Apply: paste into Supabase → SQL Editor → Run.
-- ============================================================================


-- ── event_kinds ────────────────────────────────────────────────────────────
-- Category header under which individual event instances live. `ordinal`
-- lets us preserve the order the JSON used so the sidebar lists stay
-- consistent; no natural sort order emerges from the business data.
create table if not exists public.event_kinds (
  id text primary key,
  label text not null,
  description text,
  ordinal integer
);

alter table public.event_kinds enable row level security;

drop policy if exists event_kinds_read on public.event_kinds;
create policy event_kinds_read on public.event_kinds
  for select to authenticated using (public.current_user_is_admin());
drop policy if exists event_kinds_write on public.event_kinds;
create policy event_kinds_write on public.event_kinds
  for all to authenticated
  using (public.current_user_is_admin())
  with check (public.current_user_is_admin());


-- ── event_instances ────────────────────────────────────────────────────────
-- Two kinds of instance exist and we support both with nullable columns:
--   (a) Recurring: `recurrence` is populated (weekly day, time window,
--       season start/end). `date` is null.
--   (b) One-off:   `date` is populated. `recurrence` is null.
--
-- `processing` holds the kind-specific payload for processing-day events
-- (batch id, bird counts, resources required). Other kinds may grow their
-- own jsonb payload columns later; for now we only need one.
--
-- `location` is jsonb ({name, address}) rather than a separate table
-- because the same physical location can appear across different kinds
-- (Scituate Rotary hosts both a farmers market and an egg drop) but the
-- storefront doesn't need normalized geolocation yet.
create table if not exists public.event_instances (
  id text primary key,
  kind_id text not null references public.event_kinds(id) on delete cascade,
  label text not null,
  subtitle text,
  recurrence jsonb,
  date date,
  start_time text,
  end_time text,
  location jsonb,
  processing jsonb,
  notes text,
  check ((recurrence is not null) or (date is not null))
);

create index if not exists event_instances_kind_idx
  on public.event_instances (kind_id);
create index if not exists event_instances_date_idx
  on public.event_instances (date);

alter table public.event_instances enable row level security;

drop policy if exists event_instances_read on public.event_instances;
create policy event_instances_read on public.event_instances
  for select to authenticated using (public.current_user_is_admin());
drop policy if exists event_instances_write on public.event_instances;
create policy event_instances_write on public.event_instances
  for all to authenticated
  using (public.current_user_is_admin())
  with check (public.current_user_is_admin());


-- ── product_kinds ──────────────────────────────────────────────────────────
-- SKU catalog. `size_brackets` is jsonb because each kind has its own
-- bracket set (chicken has 2-2.5 lb, 2.5-3 lb, ...; eggs just has "1
-- dozen"). Keeping them inline avoids a secondary table whose sole
-- purpose is per-parent lookup.
create table if not exists public.product_kinds (
  id text primary key,
  name text not null,
  category text,
  sale_unit text,
  source_species_id text references public.livestock_species(id) on delete set null,
  source_material text,
  yield_share_of_dressed_weight numeric,
  size_brackets jsonb not null default '[]'::jsonb,
  ordinal integer
);

alter table public.product_kinds enable row level security;

drop policy if exists product_kinds_read on public.product_kinds;
create policy product_kinds_read on public.product_kinds
  for select to authenticated using (public.current_user_is_admin());
drop policy if exists product_kinds_write on public.product_kinds;
create policy product_kinds_write on public.product_kinds
  for all to authenticated
  using (public.current_user_is_admin())
  with check (public.current_user_is_admin());


-- ── egg_lots ───────────────────────────────────────────────────────────────
-- Empty at launch. The inventory workflow (count-cartons-before-market
-- per thread_egg_inventory_model) will populate this once the egg-lot
-- entry UI exists. Columns chosen to match the JSON's lot shape
-- (collectionDate, cartonCount, eggsPerCarton, location, notes).
create table if not exists public.egg_lots (
  id uuid primary key default gen_random_uuid(),
  collection_date date not null,
  carton_count integer not null default 0,
  eggs_per_carton integer,
  location text,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists egg_lots_collection_idx
  on public.egg_lots (collection_date desc);

alter table public.egg_lots enable row level security;

drop policy if exists egg_lots_read on public.egg_lots;
create policy egg_lots_read on public.egg_lots
  for select to authenticated using (public.current_user_is_admin());
drop policy if exists egg_lots_write on public.egg_lots;
create policy egg_lots_write on public.egg_lots
  for all to authenticated
  using (public.current_user_is_admin())
  with check (public.current_user_is_admin());


-- ── chicken_lots ───────────────────────────────────────────────────────────
-- Empty at launch. Populated on broiler-processing day as part of the
-- batch-close workflow. FKs to product_kinds keep bracket/kind references
-- honest; deletion is restricted so we can't silently orphan a lot by
-- deleting its SKU.
create table if not exists public.chicken_lots (
  id uuid primary key default gen_random_uuid(),
  product_kind_id text not null references public.product_kinds(id) on delete restrict,
  size_bracket_id text not null,
  processing_date date not null,
  quantity integer not null default 0,
  location text,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists chicken_lots_processing_idx
  on public.chicken_lots (processing_date desc);
create index if not exists chicken_lots_kind_idx
  on public.chicken_lots (product_kind_id, size_bracket_id);

alter table public.chicken_lots enable row level security;

drop policy if exists chicken_lots_read on public.chicken_lots;
create policy chicken_lots_read on public.chicken_lots
  for select to authenticated using (public.current_user_is_admin());
drop policy if exists chicken_lots_write on public.chicken_lots;
create policy chicken_lots_write on public.chicken_lots
  for all to authenticated
  using (public.current_user_is_admin())
  with check (public.current_user_is_admin());


-- ============================================================================
-- Seed blocks below are generated by scripts/gen-batch3-seed.mjs from
-- src/data/nff-data.json and appended to this file at generation time.
-- ============================================================================

insert into public.event_kinds (id, label, description, ordinal)
select id, label, description, ordinal
from jsonb_to_recordset($seed$
[
  {
    "id": "farmers_market",
    "label": "Farmers markets",
    "description": "Recurring weekly farmers markets NFF attends during market season.",
    "ordinal": 1
  },
  {
    "id": "popup_event",
    "label": "Pop-up events",
    "description": "One-off selling occasions outside the regular weekly schedule.",
    "ordinal": 2
  },
  {
    "id": "egg_drop",
    "label": "Egg drop",
    "description": "Off-season customer pickup at the same farmers market site.",
    "ordinal": 3
  },
  {
    "id": "deliveries",
    "label": "Deliveries",
    "description": "Deliveries to wholesale or restaurant partners.",
    "ordinal": 4
  },
  {
    "id": "farm_visits",
    "label": "Farm visits",
    "description": "Visitors coming to the farm.",
    "ordinal": 5
  },
  {
    "id": "pickups",
    "label": "Pick-ups",
    "description": "Customer pick-ups directly from the farm.",
    "ordinal": 6
  },
  {
    "id": "processing_days",
    "label": "Processing days",
    "description": "Broiler-processing day events at Pat's Pastured. Each day processes one batch of ~275 Cornish Cross.",
    "ordinal": 7
  }
]
$seed$::jsonb) as x(id text, label text, description text, ordinal integer)
on conflict (id) do update set
  label = excluded.label,
  description = excluded.description,
  ordinal = excluded.ordinal;

insert into public.event_instances (id, kind_id, label, subtitle, recurrence, date, start_time, end_time, location, processing, notes)
select id, kind_id, label, subtitle, recurrence, date, start_time, end_time, location, processing, notes
from jsonb_to_recordset($seed$
[
  {
    "id": "scituate_rotary",
    "kind_id": "farmers_market",
    "label": "Scituate Rotary Farmers Market",
    "subtitle": null,
    "recurrence": {
      "type": "weekly",
      "dayOfWeek": 6,
      "startTime": "09:00",
      "endTime": "13:00",
      "seasonStart": "2026-05-09",
      "seasonEnd": "2026-11-01"
    },
    "date": null,
    "start_time": null,
    "end_time": null,
    "location": {
      "name": "Scituate Rotary",
      "address": "46 Institute Lane, North Scituate, RI"
    },
    "processing": null,
    "notes": null
  },
  {
    "id": "foster_market",
    "kind_id": "farmers_market",
    "label": "Foster Farmers Market",
    "subtitle": null,
    "recurrence": {
      "type": "weekly",
      "dayOfWeek": 0,
      "startTime": "09:00",
      "endTime": "12:00",
      "seasonStart": "2026-06-01",
      "seasonEnd": "2026-11-01"
    },
    "date": null,
    "start_time": null,
    "end_time": null,
    "location": {
      "name": "Foster Farmers Market",
      "address": "164 Danielson Pike, Foster, RI"
    },
    "processing": null,
    "notes": null
  },
  {
    "id": "tilted_barn",
    "kind_id": "farmers_market",
    "label": "Summer Market at Tilted Barn",
    "subtitle": null,
    "recurrence": {
      "type": "weekly",
      "dayOfWeek": 3,
      "startTime": "16:00",
      "endTime": "19:00",
      "seasonStart": "2026-06-03",
      "seasonEnd": "2026-08-26"
    },
    "date": null,
    "start_time": null,
    "end_time": null,
    "location": {
      "name": "Tilted Barn",
      "address": "One Hemsley Place, Exeter, RI 02822"
    },
    "processing": null,
    "notes": null
  },
  {
    "id": "warwick_summer_celebration",
    "kind_id": "popup_event",
    "label": "Summer Celebration",
    "subtitle": "Marketplace / Food Trucks",
    "recurrence": null,
    "date": "2026-07-10",
    "start_time": "18:00",
    "end_time": "20:30",
    "location": {
      "name": "Warwick City Hall Plaza",
      "address": "3275 Post Rd, Warwick, RI 02886"
    },
    "processing": null,
    "notes": null
  },
  {
    "id": "rocky_point_july_concert",
    "kind_id": "popup_event",
    "label": "Summer Concert",
    "subtitle": "Marketplace / Food Trucks",
    "recurrence": null,
    "date": "2026-07-18",
    "start_time": "11:00",
    "end_time": "15:00",
    "location": {
      "name": "Rocky Point",
      "address": "1 Rocky Point Ave, Warwick, RI 02889"
    },
    "processing": null,
    "notes": null
  },
  {
    "id": "warwick_july_concert",
    "kind_id": "popup_event",
    "label": "Summer Concert",
    "subtitle": "Marketplace / Food Trucks",
    "recurrence": null,
    "date": "2026-07-22",
    "start_time": "17:00",
    "end_time": "20:00",
    "location": {
      "name": "Warwick City Hall Plaza",
      "address": "3275 Post Rd, Warwick, RI 02886"
    },
    "processing": null,
    "notes": null
  },
  {
    "id": "rocky_point_august_concert",
    "kind_id": "popup_event",
    "label": "Summer Concert",
    "subtitle": "Marketplace / Food Trucks",
    "recurrence": null,
    "date": "2026-08-08",
    "start_time": "11:00",
    "end_time": "15:00",
    "location": {
      "name": "Rocky Point",
      "address": "1 Rocky Point Ave, Warwick, RI 02889"
    },
    "processing": null,
    "notes": null
  },
  {
    "id": "warwick_august_concert",
    "kind_id": "popup_event",
    "label": "Summer Concert",
    "subtitle": "Marketplace / Food Trucks",
    "recurrence": null,
    "date": "2026-08-26",
    "start_time": "17:00",
    "end_time": "20:00",
    "location": {
      "name": "Warwick City Hall Plaza",
      "address": "3275 Post Rd, Warwick, RI 02886"
    },
    "processing": null,
    "notes": null
  },
  {
    "id": "warwick_apple_fest",
    "kind_id": "popup_event",
    "label": "Apple Fest",
    "subtitle": "Concert, vendors & food trucks",
    "recurrence": null,
    "date": "2026-09-19",
    "start_time": "12:00",
    "end_time": "15:00",
    "location": {
      "name": "Warwick City Hall Plaza",
      "address": "3275 Post Rd, Warwick, RI 02886"
    },
    "processing": null,
    "notes": null
  },
  {
    "id": "scituate_egg_drop",
    "kind_id": "egg_drop",
    "label": "Scituate Egg Drop",
    "subtitle": null,
    "recurrence": {
      "type": "weekly",
      "dayOfWeek": 6,
      "startTime": "10:00",
      "endTime": "11:00",
      "seasonStart": "2026-11-02",
      "seasonEnd": "2027-04-30"
    },
    "date": null,
    "start_time": null,
    "end_time": null,
    "location": {
      "name": "Scituate Rotary",
      "address": "46 Institute Lane, North Scituate, RI"
    },
    "processing": null,
    "notes": "Continues meeting regular customers at the farmers market site after market season ends."
  },
  {
    "id": "processing_2026_05_04",
    "kind_id": "processing_days",
    "label": "Broiler processing day",
    "subtitle": null,
    "recurrence": null,
    "date": "2026-05-04",
    "start_time": "04:00",
    "end_time": "16:00",
    "location": {
      "name": "Pat's Pastured",
      "address": "830 South Road, East Greenwich, RI 02818"
    },
    "processing": {
      "batchId": null,
      "batchSize": 275,
      "breed": "Cornish Cross",
      "birdsPerCrate": 9,
      "cratesPacked": null,
      "finalCount": null,
      "cutSheetDocumentId": null,
      "resourcesRequired": [
        {
          "type": "trailer",
          "id": "flatbed_trailer"
        }
      ]
    },
    "notes": null
  },
  {
    "id": "processing_2026_06_02",
    "kind_id": "processing_days",
    "label": "Broiler processing day",
    "subtitle": null,
    "recurrence": null,
    "date": "2026-06-02",
    "start_time": "04:00",
    "end_time": "16:00",
    "location": {
      "name": "Pat's Pastured",
      "address": "830 South Road, East Greenwich, RI 02818"
    },
    "processing": {
      "batchId": null,
      "batchSize": 275,
      "breed": "Cornish Cross",
      "birdsPerCrate": 9,
      "cratesPacked": null,
      "finalCount": null,
      "cutSheetDocumentId": null,
      "resourcesRequired": [
        {
          "type": "trailer",
          "id": "flatbed_trailer"
        }
      ]
    },
    "notes": null
  },
  {
    "id": "processing_2026_06_23",
    "kind_id": "processing_days",
    "label": "Broiler processing day",
    "subtitle": null,
    "recurrence": null,
    "date": "2026-06-23",
    "start_time": "04:00",
    "end_time": "16:00",
    "location": {
      "name": "Pat's Pastured",
      "address": "830 South Road, East Greenwich, RI 02818"
    },
    "processing": {
      "batchId": null,
      "batchSize": 275,
      "breed": "Cornish Cross",
      "birdsPerCrate": 9,
      "cratesPacked": null,
      "finalCount": null,
      "cutSheetDocumentId": null,
      "resourcesRequired": [
        {
          "type": "trailer",
          "id": "flatbed_trailer"
        }
      ]
    },
    "notes": null
  },
  {
    "id": "processing_2026_07_14",
    "kind_id": "processing_days",
    "label": "Broiler processing day",
    "subtitle": null,
    "recurrence": null,
    "date": "2026-07-14",
    "start_time": "04:00",
    "end_time": "16:00",
    "location": {
      "name": "Pat's Pastured",
      "address": "830 South Road, East Greenwich, RI 02818"
    },
    "processing": {
      "batchId": null,
      "batchSize": 275,
      "breed": "Cornish Cross",
      "birdsPerCrate": 9,
      "cratesPacked": null,
      "finalCount": null,
      "cutSheetDocumentId": null,
      "resourcesRequired": [
        {
          "type": "trailer",
          "id": "flatbed_trailer"
        }
      ]
    },
    "notes": null
  },
  {
    "id": "processing_2026_08_04",
    "kind_id": "processing_days",
    "label": "Broiler processing day",
    "subtitle": null,
    "recurrence": null,
    "date": "2026-08-04",
    "start_time": "04:00",
    "end_time": "16:00",
    "location": {
      "name": "Pat's Pastured",
      "address": "830 South Road, East Greenwich, RI 02818"
    },
    "processing": {
      "batchId": null,
      "batchSize": 275,
      "breed": "Cornish Cross",
      "birdsPerCrate": 9,
      "cratesPacked": null,
      "finalCount": null,
      "cutSheetDocumentId": null,
      "resourcesRequired": [
        {
          "type": "trailer",
          "id": "flatbed_trailer"
        }
      ]
    },
    "notes": null
  },
  {
    "id": "processing_2026_08_25",
    "kind_id": "processing_days",
    "label": "Broiler processing day",
    "subtitle": null,
    "recurrence": null,
    "date": "2026-08-25",
    "start_time": "04:00",
    "end_time": "16:00",
    "location": {
      "name": "Pat's Pastured",
      "address": "830 South Road, East Greenwich, RI 02818"
    },
    "processing": {
      "batchId": null,
      "batchSize": 275,
      "breed": "Cornish Cross",
      "birdsPerCrate": 9,
      "cratesPacked": null,
      "finalCount": null,
      "cutSheetDocumentId": null,
      "resourcesRequired": [
        {
          "type": "trailer",
          "id": "flatbed_trailer"
        }
      ]
    },
    "notes": null
  },
  {
    "id": "processing_2026_09_08",
    "kind_id": "processing_days",
    "label": "Broiler processing day",
    "subtitle": null,
    "recurrence": null,
    "date": "2026-09-08",
    "start_time": "04:00",
    "end_time": "16:00",
    "location": {
      "name": "Pat's Pastured",
      "address": "830 South Road, East Greenwich, RI 02818"
    },
    "processing": {
      "batchId": null,
      "batchSize": 275,
      "breed": "Cornish Cross",
      "birdsPerCrate": 9,
      "cratesPacked": null,
      "finalCount": null,
      "cutSheetDocumentId": null,
      "resourcesRequired": [
        {
          "type": "trailer",
          "id": "flatbed_trailer"
        }
      ]
    },
    "notes": null
  },
  {
    "id": "processing_2026_10_06",
    "kind_id": "processing_days",
    "label": "Broiler processing day",
    "subtitle": null,
    "recurrence": null,
    "date": "2026-10-06",
    "start_time": "04:00",
    "end_time": "16:00",
    "location": {
      "name": "Pat's Pastured",
      "address": "830 South Road, East Greenwich, RI 02818"
    },
    "processing": {
      "batchId": null,
      "batchSize": 275,
      "breed": "Cornish Cross",
      "birdsPerCrate": 9,
      "cratesPacked": null,
      "finalCount": null,
      "cutSheetDocumentId": null,
      "resourcesRequired": [
        {
          "type": "trailer",
          "id": "flatbed_trailer"
        }
      ]
    },
    "notes": null
  }
]
$seed$::jsonb) as x(id text, kind_id text, label text, subtitle text, recurrence jsonb, date date, start_time text, end_time text, location jsonb, processing jsonb, notes text)
on conflict (id) do update set
  kind_id = excluded.kind_id,
  label = excluded.label,
  subtitle = excluded.subtitle,
  recurrence = excluded.recurrence,
  date = excluded.date,
  start_time = excluded.start_time,
  end_time = excluded.end_time,
  location = excluded.location,
  processing = excluded.processing,
  notes = excluded.notes;

insert into public.product_kinds (id, name, category, sale_unit, source_species_id, source_material, yield_share_of_dressed_weight, size_brackets, ordinal)
select id, name, category, sale_unit, source_species_id, source_material, yield_share_of_dressed_weight, size_brackets, ordinal
from jsonb_to_recordset($seed$
[
  {
    "id": "eggs",
    "name": "Eggs",
    "category": "egg",
    "sale_unit": "dozen",
    "source_species_id": "layers",
    "source_material": "egg",
    "yield_share_of_dressed_weight": null,
    "size_brackets": [
      {
        "id": "default",
        "label": "1 dozen"
      }
    ],
    "ordinal": 1
  },
  {
    "id": "whole_chicken",
    "name": "Whole chicken",
    "category": "broiler_whole",
    "sale_unit": "each",
    "source_species_id": "broilers",
    "source_material": "whole_dressed_bird",
    "yield_share_of_dressed_weight": null,
    "size_brackets": [
      {
        "id": "wc_2_25",
        "label": "2–2.5 lb",
        "minLb": 2,
        "maxLb": 2.5
      },
      {
        "id": "wc_25_3",
        "label": "2.5–3 lb",
        "minLb": 2.5,
        "maxLb": 3
      },
      {
        "id": "wc_3_35",
        "label": "3–3.5 lb",
        "minLb": 3,
        "maxLb": 3.5
      },
      {
        "id": "wc_35_4",
        "label": "3.5–4 lb",
        "minLb": 3.5,
        "maxLb": 4
      },
      {
        "id": "wc_4_45",
        "label": "4–4.5 lb",
        "minLb": 4,
        "maxLb": 4.5
      },
      {
        "id": "wc_45_5",
        "label": "4.5–5 lb",
        "minLb": 4.5,
        "maxLb": 5
      },
      {
        "id": "wc_55_6",
        "label": "5.5–6 lb",
        "minLb": 5.5,
        "maxLb": 6
      }
    ],
    "ordinal": 2
  },
  {
    "id": "bone_in_thighs",
    "name": "Bone-in thighs",
    "category": "broiler_cut",
    "sale_unit": "package",
    "source_species_id": "broilers",
    "source_material": "thigh_bone_in",
    "yield_share_of_dressed_weight": 0.17,
    "size_brackets": [
      {
        "id": "th_1_15",
        "label": "1–1.5 lb",
        "minLb": 1,
        "maxLb": 1.5
      },
      {
        "id": "th_15_2",
        "label": "1.5–2 lb",
        "minLb": 1.5,
        "maxLb": 2
      },
      {
        "id": "th_2_25",
        "label": "2–2.5 lb",
        "minLb": 2,
        "maxLb": 2.5
      }
    ],
    "ordinal": 3
  },
  {
    "id": "boneless_breast",
    "name": "Boneless breast",
    "category": "broiler_cut",
    "sale_unit": "package",
    "source_species_id": "broilers",
    "source_material": "breast_boneless",
    "yield_share_of_dressed_weight": 0.32,
    "size_brackets": [
      {
        "id": "br_05_1",
        "label": "0.5–1 lb",
        "minLb": 0.5,
        "maxLb": 1
      },
      {
        "id": "br_1_15",
        "label": "1–1.5 lb",
        "minLb": 1,
        "maxLb": 1.5
      },
      {
        "id": "br_15_2",
        "label": "1.5–2 lb",
        "minLb": 1.5,
        "maxLb": 2
      }
    ],
    "ordinal": 4
  },
  {
    "id": "wings",
    "name": "Wings",
    "category": "broiler_cut",
    "sale_unit": "package",
    "source_species_id": "broilers",
    "source_material": "wings",
    "yield_share_of_dressed_weight": 0.11,
    "size_brackets": [
      {
        "id": "wg_1_2",
        "label": "1–2 lb",
        "minLb": 1,
        "maxLb": 2
      },
      {
        "id": "wg_2_3",
        "label": "2–3 lb",
        "minLb": 2,
        "maxLb": 3
      }
    ],
    "ordinal": 5
  },
  {
    "id": "drumsticks",
    "name": "Drumsticks",
    "category": "broiler_cut",
    "sale_unit": "package",
    "source_species_id": "broilers",
    "source_material": "drumsticks",
    "yield_share_of_dressed_weight": 0.11,
    "size_brackets": [
      {
        "id": "dr_075_1",
        "label": "0.75–1 lb",
        "minLb": 0.75,
        "maxLb": 1
      },
      {
        "id": "dr_1_15",
        "label": "1–1.5 lb",
        "minLb": 1,
        "maxLb": 1.5
      },
      {
        "id": "dr_15_2",
        "label": "1.5–2 lb",
        "minLb": 1.5,
        "maxLb": 2
      }
    ],
    "ordinal": 6
  }
]
$seed$::jsonb) as x(id text, name text, category text, sale_unit text, source_species_id text, source_material text, yield_share_of_dressed_weight numeric, size_brackets jsonb, ordinal integer)
on conflict (id) do update set
  name = excluded.name,
  category = excluded.category,
  sale_unit = excluded.sale_unit,
  source_species_id = excluded.source_species_id,
  source_material = excluded.source_material,
  yield_share_of_dressed_weight = excluded.yield_share_of_dressed_weight,
  size_brackets = excluded.size_brackets,
  ordinal = excluded.ordinal;
